# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/qin/source_code/QiotApplication

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/qin/source_code/QiotApplication

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/qin/source_code/QiotApplication/CMakeFiles /home/qin/source_code/QiotApplication/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/qin/source_code/QiotApplication/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named qiotapp

# Build rule for target.
qiotapp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 qiotapp
.PHONY : qiotapp

# fast build rule for target.
qiotapp/fast:
	$(MAKE) -f CMakeFiles/qiotapp.dir/build.make CMakeFiles/qiotapp.dir/build
.PHONY : qiotapp/fast

implementation/qiotApp.o: implementation/qiotApp.cpp.o

.PHONY : implementation/qiotApp.o

# target to build an object file
implementation/qiotApp.cpp.o:
	$(MAKE) -f CMakeFiles/qiotapp.dir/build.make CMakeFiles/qiotapp.dir/implementation/qiotApp.cpp.o
.PHONY : implementation/qiotApp.cpp.o

implementation/qiotApp.i: implementation/qiotApp.cpp.i

.PHONY : implementation/qiotApp.i

# target to preprocess a source file
implementation/qiotApp.cpp.i:
	$(MAKE) -f CMakeFiles/qiotapp.dir/build.make CMakeFiles/qiotapp.dir/implementation/qiotApp.cpp.i
.PHONY : implementation/qiotApp.cpp.i

implementation/qiotApp.s: implementation/qiotApp.cpp.s

.PHONY : implementation/qiotApp.s

# target to generate assembly for a file
implementation/qiotApp.cpp.s:
	$(MAKE) -f CMakeFiles/qiotapp.dir/build.make CMakeFiles/qiotapp.dir/implementation/qiotApp.cpp.s
.PHONY : implementation/qiotApp.cpp.s

implementation/window_ui/backends/imgui_impl_glfw.o: implementation/window_ui/backends/imgui_impl_glfw.cpp.o

.PHONY : implementation/window_ui/backends/imgui_impl_glfw.o

# target to build an object file
implementation/window_ui/backends/imgui_impl_glfw.cpp.o:
	$(MAKE) -f CMakeFiles/qiotapp.dir/build.make CMakeFiles/qiotapp.dir/implementation/window_ui/backends/imgui_impl_glfw.cpp.o
.PHONY : implementation/window_ui/backends/imgui_impl_glfw.cpp.o

implementation/window_ui/backends/imgui_impl_glfw.i: implementation/window_ui/backends/imgui_impl_glfw.cpp.i

.PHONY : implementation/window_ui/backends/imgui_impl_glfw.i

# target to preprocess a source file
implementation/window_ui/backends/imgui_impl_glfw.cpp.i:
	$(MAKE) -f CMakeFiles/qiotapp.dir/build.make CMakeFiles/qiotapp.dir/implementation/window_ui/backends/imgui_impl_glfw.cpp.i
.PHONY : implementation/window_ui/backends/imgui_impl_glfw.cpp.i

implementation/window_ui/backends/imgui_impl_glfw.s: implementation/window_ui/backends/imgui_impl_glfw.cpp.s

.PHONY : implementation/window_ui/backends/imgui_impl_glfw.s

# target to generate assembly for a file
implementation/window_ui/backends/imgui_impl_glfw.cpp.s:
	$(MAKE) -f CMakeFiles/qiotapp.dir/build.make CMakeFiles/qiotapp.dir/implementation/window_ui/backends/imgui_impl_glfw.cpp.s
.PHONY : implementation/window_ui/backends/imgui_impl_glfw.cpp.s

implementation/window_ui/backends/imgui_impl_opengl3.o: implementation/window_ui/backends/imgui_impl_opengl3.cpp.o

.PHONY : implementation/window_ui/backends/imgui_impl_opengl3.o

# target to build an object file
implementation/window_ui/backends/imgui_impl_opengl3.cpp.o:
	$(MAKE) -f CMakeFiles/qiotapp.dir/build.make CMakeFiles/qiotapp.dir/implementation/window_ui/backends/imgui_impl_opengl3.cpp.o
.PHONY : implementation/window_ui/backends/imgui_impl_opengl3.cpp.o

implementation/window_ui/backends/imgui_impl_opengl3.i: implementation/window_ui/backends/imgui_impl_opengl3.cpp.i

.PHONY : implementation/window_ui/backends/imgui_impl_opengl3.i

# target to preprocess a source file
implementation/window_ui/backends/imgui_impl_opengl3.cpp.i:
	$(MAKE) -f CMakeFiles/qiotapp.dir/build.make CMakeFiles/qiotapp.dir/implementation/window_ui/backends/imgui_impl_opengl3.cpp.i
.PHONY : implementation/window_ui/backends/imgui_impl_opengl3.cpp.i

implementation/window_ui/backends/imgui_impl_opengl3.s: implementation/window_ui/backends/imgui_impl_opengl3.cpp.s

.PHONY : implementation/window_ui/backends/imgui_impl_opengl3.s

# target to generate assembly for a file
implementation/window_ui/backends/imgui_impl_opengl3.cpp.s:
	$(MAKE) -f CMakeFiles/qiotapp.dir/build.make CMakeFiles/qiotapp.dir/implementation/window_ui/backends/imgui_impl_opengl3.cpp.s
.PHONY : implementation/window_ui/backends/imgui_impl_opengl3.cpp.s

implementation/window_ui/imgui.o: implementation/window_ui/imgui.cpp.o

.PHONY : implementation/window_ui/imgui.o

# target to build an object file
implementation/window_ui/imgui.cpp.o:
	$(MAKE) -f CMakeFiles/qiotapp.dir/build.make CMakeFiles/qiotapp.dir/implementation/window_ui/imgui.cpp.o
.PHONY : implementation/window_ui/imgui.cpp.o

implementation/window_ui/imgui.i: implementation/window_ui/imgui.cpp.i

.PHONY : implementation/window_ui/imgui.i

# target to preprocess a source file
implementation/window_ui/imgui.cpp.i:
	$(MAKE) -f CMakeFiles/qiotapp.dir/build.make CMakeFiles/qiotapp.dir/implementation/window_ui/imgui.cpp.i
.PHONY : implementation/window_ui/imgui.cpp.i

implementation/window_ui/imgui.s: implementation/window_ui/imgui.cpp.s

.PHONY : implementation/window_ui/imgui.s

# target to generate assembly for a file
implementation/window_ui/imgui.cpp.s:
	$(MAKE) -f CMakeFiles/qiotapp.dir/build.make CMakeFiles/qiotapp.dir/implementation/window_ui/imgui.cpp.s
.PHONY : implementation/window_ui/imgui.cpp.s

implementation/window_ui/imgui_demo.o: implementation/window_ui/imgui_demo.cpp.o

.PHONY : implementation/window_ui/imgui_demo.o

# target to build an object file
implementation/window_ui/imgui_demo.cpp.o:
	$(MAKE) -f CMakeFiles/qiotapp.dir/build.make CMakeFiles/qiotapp.dir/implementation/window_ui/imgui_demo.cpp.o
.PHONY : implementation/window_ui/imgui_demo.cpp.o

implementation/window_ui/imgui_demo.i: implementation/window_ui/imgui_demo.cpp.i

.PHONY : implementation/window_ui/imgui_demo.i

# target to preprocess a source file
implementation/window_ui/imgui_demo.cpp.i:
	$(MAKE) -f CMakeFiles/qiotapp.dir/build.make CMakeFiles/qiotapp.dir/implementation/window_ui/imgui_demo.cpp.i
.PHONY : implementation/window_ui/imgui_demo.cpp.i

implementation/window_ui/imgui_demo.s: implementation/window_ui/imgui_demo.cpp.s

.PHONY : implementation/window_ui/imgui_demo.s

# target to generate assembly for a file
implementation/window_ui/imgui_demo.cpp.s:
	$(MAKE) -f CMakeFiles/qiotapp.dir/build.make CMakeFiles/qiotapp.dir/implementation/window_ui/imgui_demo.cpp.s
.PHONY : implementation/window_ui/imgui_demo.cpp.s

implementation/window_ui/imgui_draw.o: implementation/window_ui/imgui_draw.cpp.o

.PHONY : implementation/window_ui/imgui_draw.o

# target to build an object file
implementation/window_ui/imgui_draw.cpp.o:
	$(MAKE) -f CMakeFiles/qiotapp.dir/build.make CMakeFiles/qiotapp.dir/implementation/window_ui/imgui_draw.cpp.o
.PHONY : implementation/window_ui/imgui_draw.cpp.o

implementation/window_ui/imgui_draw.i: implementation/window_ui/imgui_draw.cpp.i

.PHONY : implementation/window_ui/imgui_draw.i

# target to preprocess a source file
implementation/window_ui/imgui_draw.cpp.i:
	$(MAKE) -f CMakeFiles/qiotapp.dir/build.make CMakeFiles/qiotapp.dir/implementation/window_ui/imgui_draw.cpp.i
.PHONY : implementation/window_ui/imgui_draw.cpp.i

implementation/window_ui/imgui_draw.s: implementation/window_ui/imgui_draw.cpp.s

.PHONY : implementation/window_ui/imgui_draw.s

# target to generate assembly for a file
implementation/window_ui/imgui_draw.cpp.s:
	$(MAKE) -f CMakeFiles/qiotapp.dir/build.make CMakeFiles/qiotapp.dir/implementation/window_ui/imgui_draw.cpp.s
.PHONY : implementation/window_ui/imgui_draw.cpp.s

implementation/window_ui/imgui_tables.o: implementation/window_ui/imgui_tables.cpp.o

.PHONY : implementation/window_ui/imgui_tables.o

# target to build an object file
implementation/window_ui/imgui_tables.cpp.o:
	$(MAKE) -f CMakeFiles/qiotapp.dir/build.make CMakeFiles/qiotapp.dir/implementation/window_ui/imgui_tables.cpp.o
.PHONY : implementation/window_ui/imgui_tables.cpp.o

implementation/window_ui/imgui_tables.i: implementation/window_ui/imgui_tables.cpp.i

.PHONY : implementation/window_ui/imgui_tables.i

# target to preprocess a source file
implementation/window_ui/imgui_tables.cpp.i:
	$(MAKE) -f CMakeFiles/qiotapp.dir/build.make CMakeFiles/qiotapp.dir/implementation/window_ui/imgui_tables.cpp.i
.PHONY : implementation/window_ui/imgui_tables.cpp.i

implementation/window_ui/imgui_tables.s: implementation/window_ui/imgui_tables.cpp.s

.PHONY : implementation/window_ui/imgui_tables.s

# target to generate assembly for a file
implementation/window_ui/imgui_tables.cpp.s:
	$(MAKE) -f CMakeFiles/qiotapp.dir/build.make CMakeFiles/qiotapp.dir/implementation/window_ui/imgui_tables.cpp.s
.PHONY : implementation/window_ui/imgui_tables.cpp.s

implementation/window_ui/imgui_widgets.o: implementation/window_ui/imgui_widgets.cpp.o

.PHONY : implementation/window_ui/imgui_widgets.o

# target to build an object file
implementation/window_ui/imgui_widgets.cpp.o:
	$(MAKE) -f CMakeFiles/qiotapp.dir/build.make CMakeFiles/qiotapp.dir/implementation/window_ui/imgui_widgets.cpp.o
.PHONY : implementation/window_ui/imgui_widgets.cpp.o

implementation/window_ui/imgui_widgets.i: implementation/window_ui/imgui_widgets.cpp.i

.PHONY : implementation/window_ui/imgui_widgets.i

# target to preprocess a source file
implementation/window_ui/imgui_widgets.cpp.i:
	$(MAKE) -f CMakeFiles/qiotapp.dir/build.make CMakeFiles/qiotapp.dir/implementation/window_ui/imgui_widgets.cpp.i
.PHONY : implementation/window_ui/imgui_widgets.cpp.i

implementation/window_ui/imgui_widgets.s: implementation/window_ui/imgui_widgets.cpp.s

.PHONY : implementation/window_ui/imgui_widgets.s

# target to generate assembly for a file
implementation/window_ui/imgui_widgets.cpp.s:
	$(MAKE) -f CMakeFiles/qiotapp.dir/build.make CMakeFiles/qiotapp.dir/implementation/window_ui/imgui_widgets.cpp.s
.PHONY : implementation/window_ui/imgui_widgets.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... qiotapp"
	@echo "... implementation/qiotApp.o"
	@echo "... implementation/qiotApp.i"
	@echo "... implementation/qiotApp.s"
	@echo "... implementation/window_ui/backends/imgui_impl_glfw.o"
	@echo "... implementation/window_ui/backends/imgui_impl_glfw.i"
	@echo "... implementation/window_ui/backends/imgui_impl_glfw.s"
	@echo "... implementation/window_ui/backends/imgui_impl_opengl3.o"
	@echo "... implementation/window_ui/backends/imgui_impl_opengl3.i"
	@echo "... implementation/window_ui/backends/imgui_impl_opengl3.s"
	@echo "... implementation/window_ui/imgui.o"
	@echo "... implementation/window_ui/imgui.i"
	@echo "... implementation/window_ui/imgui.s"
	@echo "... implementation/window_ui/imgui_demo.o"
	@echo "... implementation/window_ui/imgui_demo.i"
	@echo "... implementation/window_ui/imgui_demo.s"
	@echo "... implementation/window_ui/imgui_draw.o"
	@echo "... implementation/window_ui/imgui_draw.i"
	@echo "... implementation/window_ui/imgui_draw.s"
	@echo "... implementation/window_ui/imgui_tables.o"
	@echo "... implementation/window_ui/imgui_tables.i"
	@echo "... implementation/window_ui/imgui_tables.s"
	@echo "... implementation/window_ui/imgui_widgets.o"
	@echo "... implementation/window_ui/imgui_widgets.i"
	@echo "... implementation/window_ui/imgui_widgets.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

